from enum import StrEnum


class RoleArchetype(StrEnum):
    TECHNICAL_PRODUCT = "technical_product"
    TECHNICAL_PROGRAM = "technical_program"
    SYSTEMS_INTEGRATION = "systems_integration"
    AI_PRODUCT = "ai_product"
    AUTONOMOUS_SYSTEMS = "autonomous_systems"
    ROBOTICS_PRODUCT = "robotics_product"
    ROBOTICS = "robotics"
    DEEPTECH_PRODUCT = "deeptech_product"
    DEEPTECH = "deeptech"
    DEFENCE_TECH_PRODUCT = "defence_tech_product"
    DEFENCE_AEROSPACE = "defence_aerospace"
    PRODUCT_STRATEGY = "product_strategy"
    TECHNOLOGY_STRATEGY = "technology_strategy"
    AI_TRANSFORMATION = "ai_transformation"
    PLATFORM_PRODUCT = "platform_product"
    PRODUCT_LEADERSHIP = "product_leadership"
    PRODUCT_OPERATIONS = "product_operations"
    ENGINEERING_PROGRAM = "engineering_program"
    SYSTEMS_LEADERSHIP = "systems_leadership"
    TECHNICAL_PARTNERSHIPS = "technical_partnerships"
    SOLUTION_ARCHITECTURE = "solution_architecture"
    FIELD_APPLICATIONS = "field_applications"
    CUSTOMER_ENGINEERING = "customer_engineering"
    INNOVATION = "innovation"
    MOBILITY = "mobility"
    SOLUTIONS_ARCHITECTURE = "solutions_architecture"
    UNKNOWN = "unknown"
